### ISSUE TITLE
Broken example in documentation

### ISSUE THREAD

**Issue by Eloitor** [KnorrFG/datasheet#4]
I tried to run the example in the documentation and I got
```
NameError: name 'HLayout' is not defined
```

By the way, the look of the generated page seems to be outdated too. I got arrows next to each heading, but the example in https://datasheet.readthedocs.io/en/latest/ doesn't show them.

**Comment by Eloitor** [comment]
Also the import `datasheet.MD` is unused in that example.

**Comment by KnorrFG** [comment]
Hey, thank you for your report. It's fixed now.

**Comment by Eloitor** [comment]
Thanks for the quick fixes. By the way, I think you could add a URL to the project. (The settings menu next to "About")
It could either point to https://datasheet.readthedocs.io/en/latest/ or https://pypi.org/project/datasheet/

**Comment by Eloitor** [comment]
And you could use https://sphinx-copybutton.readthedocs.io/en/latest/ for the documentation, it makes it easier to copy the example :)

**Comment by KnorrFG** [comment]
Which settings menu do you mean?

**Comment by Eloitor** [comment]
Go to: https://github.com/KnorrFG/datasheet
on the right there is the text "About" and the description. On the right of that there is an unlabeled settings button

**Comment by KnorrFG** [comment]
I see, thanks, done.

**Comment by Eloitor** [comment]
The example has the line `import nibabel as nib` which can be removed :)

**Comment by Eloitor** [comment]
as well as `import numpy as np`

**Comment by KnorrFG** [comment]
thanks

**Comment by Eloitor** [comment]
and this line can also be removed, otherwise it asks for nibabel as a dependency:

https://github.com/KnorrFG/datasheet/blob/master/datasheet/sheet.py#L8

**Comment by KnorrFG** [comment]
you know what, I'm going to let you alone with this code for a while, and fix whatever you find tonight ^^

**Comment by Eloitor** [comment]
I think that's all :')
